# Generated by Django 3.2 on 2021-04-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.customuser')),
                ('mobile_number', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=20)),
            ],
        ),
    ]
