# Generated by Django 3.2 on 2021-05-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.CharField(default='admin', max_length=250),
        ),
        migrations.AddField(
            model_name='room',
            name='vendor',
            field=models.CharField(default='admin', max_length=250),
        ),
    ]
